gold:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      location: US
      keyfile: "{{ env_var('DBT_PROFILE_KEYFILE') }}"
      project: taxi-rides-ny-412407
      dataset: development
      threads: 1
      job_execution_timeout_seconds: 200
      priority: interactive
      job_retries: 1
    staging:
      type: bigquery
      method: service-account
      location: US
      keyfile: "{{ env_var('DBT_PROFILE_KEYFILE') }}"
      project: taxi-rides-ny-412407
      dataset: gold_staging
      threads: 1
      job_execution_timeout_seconds: 200
      priority: interactive
      job_retries: 1
    prod:
      type: bigquery
      method: service-account
      location: US
      keyfile: "{{ env_var('DBT_PROFILE_KEYFILE') }}"
      project: taxi-rides-ny-412407
      dataset: gold
      threads: 1
      job_execution_timeout_seconds: 200
      priority: interactive
      job_retries: 1
      
      
      
      
      
      
      
