name: Deploy dbt build to production on push to main

on:
  push:
    branches:
      - main

# Setting some Env variables to work  with profiles.yml
env:
  # dbt env variables used in your dbt profiles.yml
  DBT_PROFILES_DIR: ./
  DBT_PROFILE_KEYFILE: /tmp/google/google-service-account.json

  # Name of GCP project
  GCP_PROJECT: taxi-rides-ny-412407

  # the contents of the keyfile pulled from GitHub Actions secrets
  KEYFILE_CONTENTS: ${{secrets.KEYFILE_CONTENTS}}

jobs:
  dbt_run:
    name: Scheduled dbt refresh and test
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    # Steps of the workflow:
    steps:

      # Prep Google keyfile
      - run: mkdir -p "$(dirname $DBT_PROFILE_KEYFILE)"
      - run: echo "$KEYFILE_CONTENTS" > $DBT_PROFILE_KEYFILE

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install dbt
        run: |
          pip install dbt-core
          pip install dbt-bigquery

      - name: Silver - Package dbt dependancies
        working-directory: ./transformations/silver
        run: dbt deps

      - name: Silver - est connection to BigQuery
        working-directory: ./transformations/silver
        run: dbt debug --target prod

      - name: Silver - Build dbt repository
        working-directory: ./transformations/silver
        run: dbt build --target prod
        
      - name: Gold - Package dbt dependancies
        working-directory: ./transformations/gold
        run: dbt deps

      - name: Gold - Test connection to BigQuery
        working-directory: ./transformations/gold
        run: dbt debug --target prod

      - name: Gold - Build dbt repository
        working-directory: ./transformations/gold
        run: dbt build --target prod