name: Test dbt build on pull request

on:
  pull_request:
    branches:
      - main

# Setting some Env variables to work  with profiles.yml
env:
  # dbt env variables used in your dbt profiles.yml
  DBT_PROFILES_DIR: ./transformations/gold
  DBT_PROFILE_KEYFILE: /tmp/google/google-service-account.json

  # the contents of the keyfile pulled from GitHub Actions secrets
  KEYFILE_CONTENTS: ${{secrets.KEYFILE_CONTENTS}}

jobs:
  dbt_run:
    name: Scheduled dbt refresh and test
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    # Steps of the workflow:
    steps:

      # Prep Google keyfile
      - run: mkdir -p "$(dirname $DBT_PROFILE_KEYFILE)"
      - run: echo "$KEYFILE_CONTENTS" > $DBT_PROFILE_KEYFILE

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install dbt
        run: |
          pip install dbt-core
          pip install dbt-bigquery

      - name: Package dbt dependancies
        working-directory: ./transformations/gold
        run: dbt deps --profiles-dir ./

      - name: Test connection to BigQuery
        working-directory: ./transformations/gold
        run: dbt debug --target staging --profiles-dir ./

      - name: Build dbt repository
        working-directory: ./transformations/gold
        run: dbt build --target staging --profiles-dir ./